# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_base_old.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *
from PySide2.QtGui import *
import icon_rc


class MySwitch(QPushButton):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.setCheckable(True)
        self.setMinimumWidth(100)
        self.setMinimumHeight(22)
        
    def paintEvent(self, event):
        label = "ON" if self.isChecked() else "OFF"
        bg_color = QColor.fromRgb(3,155,229) if self.isChecked() else QColor.fromRgb(50,50,50)
        #label.setStyleSheet("color:black;") if self.isChecked() else label.setStyleSheet("color:white;")
        
        radius = 11
        width = 50
        center = self.rect().center()

        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.translate(center)
        painter.setBrush(QColor(0,0,0))

        pen = QPen(QColor.fromRgb(225,225,225))
        pen.setWidth(2)
        painter.setPen(pen)

        painter.drawRoundedRect(QRect(-width, -radius, 2*width, 2*radius), radius, radius)
        painter.setBrush(QBrush(bg_color))
        sw_rect = QRect(-radius, -radius, width + radius, 2*radius)
        if not self.isChecked():
            sw_rect.moveLeft(-width)
        painter.drawRoundedRect(sw_rect, radius, radius)
        painter.drawText(sw_rect, Qt.AlignCenter, label)



class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        #MainWindow2.resize(1000, 720)
        #MainWindow2.setMinimumSize(QSize(1000, 720))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 0))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(66, 73, 90, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(55, 61, 75, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(22, 24, 30, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(29, 32, 40, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        brush6 = QBrush(QColor(210, 210, 210, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush7)
        brush8 = QBrush(QColor(85, 170, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Active, QPalette.Link, brush8)
        brush9 = QBrush(QColor(255, 0, 127, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush10 = QBrush(QColor(44, 49, 60, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush10)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush11 = QBrush(QColor(210, 210, 210, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush10)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        brush12 = QBrush(QColor(210, 210, 210, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        brush13 = QBrush(QColor(51, 153, 255, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush13)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush10)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush14 = QBrush(QColor(210, 210, 210, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        MainWindow2.setPalette(palette)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow2.setFont(font)
        MainWindow2.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"	color: #ffffff;\n"
"	background-color: rgba(27, 29, 35, 160);\n"
"	border: 1px solid rgb(40, 40, 40);\n"
"	border-radius: 2px;\n"
"}")
        self.centralwidget = QWidget(MainWindow2)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_main = QFrame(self.centralwidget)
        self.frame_main.setStyleSheet(u"/* LINE EDIT */\n"
"QLineEdit {\n"
"	background-color: rgb(27, 29, 35);\n"
"	border-radius: 5px;\n"
"	border: 2px solid rgb(27, 29, 35);\n"
"	padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"	border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"	border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"	border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"	border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"	border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
""
                        "	border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"	border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"	border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {	\n"
"	background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"	border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"	border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"	border: none;\n"
"    background: rgb(55, 63"
                        ", 77);\n"
"     height: 20px;\n"
"	border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"	border: 3px solid rgb(52, 59, 72);	\n"
"	background-image: url(:/16x16/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"	width: 15px;\n"
"	height: 15px;\n"
"	border-radius"
                        ": 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"	border: 3px solid rgb(52, 59, 72);	\n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"	background-color: rgb(27, 29, 35);\n"
"	border-radius: 5px;\n"
"	border: 2px solid rgb(27, 29, 35);\n"
"	padding: 5px;\n"
"	padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"	border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"	subcontrol-origin: padding;\n"
"	subcontrol-position: top right;\n"
"	width: 25px; \n"
"	border-left-width: 3px;\n"
"	border-left-color: rgba(39, 44, 54, 150);\n"
"	border-left-style: solid;\n"
"	border-top-right-radius: 3px;\n"
"	border-bottom-right-radius: 3px;	\n"
"	background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"	background-position: center;\n"
"	background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"	color: rgb("
                        "85, 170, 255);	\n"
"	background-color: rgb(27, 29, 35);\n"
"	padding: 10px;\n"
"	selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"	margin: 0px;\n"
"	background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"	background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"	border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"	background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"	background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:verti"
                        "cal {\n"
"    background-color: rgb(85, 170, 255);\n"
"	border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"	border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QFrame.NoFrame)
        self.frame_main.setFrameShadow(QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QFrame(self.frame_main)
        self.frame_top.setMaximumHeight(65)
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QFrame.NoFrame)
        self.frame_top.setMinimumSize(QSize(0, 65))
        self.frame_top.setFrameShadow(QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_toggle = QFrame(self.frame_top)
        self.frame_toggle.setMaximumWidth(65)
        self.frame_toggle.setMaximumHeight(65)
        self.frame_toggle.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_toggle.setFrameShape(QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_3 = QVBoxLayout(self.frame_toggle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_toggle_menu = QPushButton(self.frame_toggle)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu.setSizePolicy(sizePolicy)
        self.btn_toggle_menu.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-menu.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color:rgb(50, 50, 50);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu.setText("")
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.verticalLayout_3.addWidget(self.btn_toggle_menu)
        self.horizontalLayout_3.addWidget(self.frame_toggle)
        self.frame_top_right = QFrame(self.frame_top)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_2 = QVBoxLayout(self.frame_top_right)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_btns = QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumHeight(40)
        self.frame_top_btns.setStyleSheet("background-color: rgba(33, 33, 35, 200);")
        self.frame_top_btns.setFrameShape(QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QFrame(self.frame_top_btns)
        self.frame_label_top_btns.setFrameShape(QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QSize(40, 40))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame_icon_top_bar.setFrameShape(QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QLabel(self.frame_label_top_btns)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"margin-left: 5px;")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QFrame(self.frame_top_btns)
        self.frame_btns_right.setMaximumSize(QSize(120, 40))
        self.frame_btns_right.setFrameShape(QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QPushButton(self.frame_btns_right)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(":/16x16/icons/16x16/cil-window-minimize.png"), QIcon.Normal, QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QPushButton(self.frame_btns_right)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/16x16/icons/16x16/cil-window-maximize.png"), QIcon.Normal, QIcon.Off)
        self.btn_maximize_restore.setIcon(icon1)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_5.addWidget(self.btn_maximize_restore)
        self.btn_close = QPushButton(self.frame_btns_right)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/16x16/icons/16x16/cil-x.png"), QIcon.Normal, QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right)
        self.verticalLayout_2.addWidget(self.frame_top_btns)
        self.frame_top_info = QFrame(self.frame_top_right)
        self.frame_top_info.setStyleSheet("background-color:rgb(91, 91, 91);")
        self.frame_top_info.setFrameShape(QFrame.NoFrame)
        self.frame_top_info.setFrameShadow(QFrame.Raised)
        self.frame_top_info.setObjectName("frame_top_info")
        self.horizontalLayout_8 = QHBoxLayout(self.frame_top_info)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_top_info_1 = QLabel(self.frame_top_info)
        font = QFont()
        font.setFamily("Segoe UI")
        self.label_top_info_1.setFont(font)
        self.label_top_info_1.setStyleSheet("color: rgb(200,200,200);")
        self.label_top_info_1.setObjectName("label_top_info_1")
        self.horizontalLayout_8.addWidget(self.label_top_info_1)
        self.label_top_info_2 = QLabel(self.frame_top_info)
        self.label_top_info_2.setMinimumSize(QSize(0, 0))
        self.label_top_info_2.setMaximumSize(QSize(150, 25))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_top_info_2.setFont(font)
        self.label_top_info_2.setStyleSheet("color: rgb(200, 200, 200);")
        self.label_top_info_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_top_info_2.setObjectName("label_top_info_2")
        self.horizontalLayout_8.addWidget(self.label_top_info_2)
        self.verticalLayout_2.addWidget(self.frame_top_info)
        self.horizontalLayout_3.addWidget(self.frame_top_right)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QFrame(self.frame_main)
        self.frame_center.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.frame_center.setFrameShape(QFrame.NoFrame)
        self.frame_center.setFrameShadow(QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QFrame(self.frame_center)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMaximumWidth(70)
        self.frame_left_menu.setLayoutDirection(Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("background-color:rgb(50, 50, 50);")
        self.frame_left_menu.setFrameShape(QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_5 = QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_menus = QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.btn_open_file = QPushButton(self.frame_menus)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_file.sizePolicy().hasHeightForWidth())
        self.btn_open_file.setSizePolicy(sizePolicy)
        self.btn_open_file.setMinimumSize(QSize(0, 60))
        font = QFont()
        font.setFamily("Segoe UI")
        self.btn_open_file.setFont(font)
        self.btn_open_file.setLayoutDirection(Qt.LeftToRight)
        self.btn_open_file.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/20x20/icons/20x20/cil-home.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(50, 50, 50);\n"
"    background-color: rgb(50, 50, 50);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91, 91, 91);\n"
"    border-left: 28px solid rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.btn_open_file.setObjectName("btn_open_file")
        #self.layout_menus.addWidget(self.btn_open_file)
        self.btn_mouth = QPushButton(self.frame_menus)
        self.btn_mouth.setMinimumSize(QSize(0, 60))
        self.btn_mouth.setStyleSheet("QPushButton {\n"
"    background-image: url(:/20x20/icons/20x20/mouth.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(50, 50, 50);\n"
"    background-color: :rgb(50, 50, 50);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(91, 91, 91);\n"
"    border-left: 28px solid rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.btn_mouth.setObjectName("btn_mouth")
        self.layout_menus.addWidget(self.btn_mouth)
        self.btn_new_user = QPushButton(self.frame_menus)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_new_user.sizePolicy().hasHeightForWidth())
        self.btn_new_user.setSizePolicy(sizePolicy)
        self.btn_new_user.setMinimumSize(QSize(0, 60))
        font = QFont()
        font.setFamily("Segoe UI")
        self.btn_new_user.setFont(font)
        self.btn_new_user.setLayoutDirection(Qt.LeftToRight)
        self.btn_new_user.setStyleSheet("QPushButton {\n"
"    background-image: url(:/16x16/icons/16x16/cil-eye-open.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(50, 50, 50);\n"
"    background-color: rgb(50, 50, 50);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91, 91, 91);\n"
"    border-left: 28px solid rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.btn_new_user.setObjectName("btn_new_user")
        self.layout_menus.addWidget(self.btn_new_user)
        self.verticalLayout_5.addWidget(self.frame_menus, 0, Qt.AlignTop)
        self.frame_extra_menus = QFrame(self.frame_left_menu)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setFrameShape(QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.layout_menu_bottom = QVBoxLayout(self.frame_extra_menus)
        self.layout_menu_bottom.setContentsMargins(0, 0, 0, 0)
        self.layout_menu_bottom.setSpacing(10)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.label_user_icon = QLabel(self.frame_extra_menus)
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_icon.sizePolicy().hasHeightForWidth())
        self.label_user_icon.setSizePolicy(sizePolicy)
        self.label_user_icon.setMinimumSize(QSize(60, 60))
        #self.label_user_icon.setMaximumSize(QSize(60, 60))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_icon.setFont(font)
        self.label_user_icon.setStyleSheet("QLabel {\n"
"    border-radius: 30px;\n"
"    background-color:rgb(20, 255, 236);\n"
"    color:black\n"
";\n"
"}")
        self.label_user_icon.setAlignment(Qt.AlignCenter)
        self.label_user_icon.setObjectName("label_user_icon")
        self.layout_menu_bottom.addWidget(self.label_user_icon, 0, Qt.AlignHCenter)
        self.btn_settings = QPushButton(self.frame_extra_menus)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        self.btn_settings.setMinimumSize(QSize(0, 60))
        font = QFont()
        font.setFamily("Segoe UI")
        self.btn_settings.setFont(font)
        self.btn_settings.setLayoutDirection(Qt.LeftToRight)
        self.btn_settings.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/20x20/icons/20x20/cil-settings.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 26px solid rgb(50, 50, 50);\n"
"    background-color: rgb(50, 50, 50);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(91, 91, 91);\n"
"    border-left: 26px solid rgb(91, 91, 91);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 26px solid rgb(85, 170, 255);\n"
"}")
        self.btn_settings.setObjectName("btn_settings")
        self.layout_menu_bottom.addWidget(self.btn_settings)
        self.verticalLayout_5.addWidget(self.frame_extra_menus, 0, Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_content_right = QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("background-color:rgb(20, 20, 20)")
        self.frame_content_right.setFrameShape(QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_4 = QVBoxLayout(self.frame_content_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_content = QFrame(self.frame_content_right)
        self.frame_content.setFrameShape(QFrame.NoFrame)
        self.frame_content.setFrameShadow(QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_9 = QVBoxLayout(self.frame_content)
        self.verticalLayout_9.setContentsMargins(0,0,0,0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QStackedWidget(self.frame_content)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QWidget()
        self.page_home.setLayoutDirection(Qt.LeftToRight)
        self.page_home.setStyleSheet("")
        self.page_home.setObjectName("page_home")
        self.horizontalLayout = QHBoxLayout(self.page_home)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.face_pane = QWidget(self.page_home)
        self.face_pane.setStyleSheet("QWidget{\n"
"border-right:3px solid rgb(0, 71, 75);\n"
"margin:0px;\n"
"}")
        self.face_pane.setObjectName("face_pane")
        self.gridLayout_5 = QGridLayout(self.face_pane)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lab_face = QLabel(self.face_pane)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.lab_face.setFont(font)
        self.lab_face.setStyleSheet("border:none\n"
";")
        self.lab_face.setObjectName("lab_face")
        self.gridLayout_5.addWidget(self.lab_face, 0, 0, 1, 1)
        self.extra2 = QLabel(self.face_pane)
        self.extra2.setStyleSheet("border:none;")
        self.extra2.setText("")
        self.extra2.setObjectName("extra2")
        self.gridLayout_5.addWidget(self.extra2, 2, 0, 1, 1)
        self.label_6 = QLabel(self.face_pane)
        self.label_6.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setScaledContents(True)
        #self.label_6.setMaximumSize(QSize(416, 16777215))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("border:2px solid rgb(200,200,200);\n"
"margin:0px;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.extra1 = QLabel(self.face_pane)
        self.extra1.setStyleSheet("border:none;")
        self.extra1.setText("")
        self.extra1.setObjectName("extra1")
        self.gridLayout_5.addWidget(self.extra1, 5, 0, 1, 1)
        self.widget_8 = QWidget(self.face_pane)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_5.addWidget(self.widget_8, 4, 0, 1, 1)
        self.widget_13 = QWidget(self.face_pane)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_5.addWidget(self.widget_13, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.face_pane)
        self.line = QFrame(self.page_home)
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setStyleSheet("Line{\n"
"color: rgb(85, 0, 127);\n"
"width:5px;\n"
"}")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.driver_status = QWidget(self.page_home)
        self.driver_status.setStyleSheet("QWidget{\n"
"border-color: rgb(0, 71, 75);\n"
"}")
        self.driver_status.setObjectName("driver_status")
        self.gridLayout = QGridLayout(self.driver_status)
        self.gridLayout.setObjectName("gridLayout")
        self.title_face = QLabel(self.driver_status)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.title_face.setFont(font)
        self.title_face.setAlignment(Qt.AlignCenter)
        self.title_face.setObjectName("title_face")
        self.gridLayout.addWidget(self.title_face, 0, 0, 1, 1)
        self.general = QLabel(self.driver_status)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.general.setFont(font)
        self.general.setObjectName("general")
        self.gridLayout.addWidget(self.general, 1, 0, 1, 1)
        self.eye_2 = QLabel(self.driver_status)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.eye_2.setFont(font)
        self.eye_2.setObjectName("eye_2")
        self.gridLayout.addWidget(self.eye_2, 2, 0, 1, 1)
        self.mouth = QLabel(self.driver_status)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.mouth.setFont(font)
        self.mouth.setObjectName("mouth")
        self.gridLayout.addWidget(self.mouth, 3, 0, 1, 1)
        self.extra3 = QLabel(self.driver_status)
        self.extra3.setText("")
        self.extra3.setObjectName("extra3")
        self.gridLayout.addWidget(self.extra3, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.driver_status)
        self.stackedWidget.addWidget(self.page_home)
        self.eye = QWidget()
        self.eye.setEnabled(True)
        self.eye.setObjectName("eye")
        self.eye.setLayoutDirection(Qt.LeftToRight)
        self.horizontalLayout_11 = QHBoxLayout(self.eye)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_9 = QWidget(self.eye)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_3 = QGridLayout(self.widget_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_20 = QLabel(self.widget_9)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QSize(0, 0))
        self.label_20.setStyleSheet("border:2px solid white;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_23 = QLabel(self.widget_9)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_22 = QLabel(self.widget_9)
        font = QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(25)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_8 = QLabel(self.widget_9)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(30)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.widget_14 = QWidget(self.widget_9)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_3.addWidget(self.widget_14, 4, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.widget_9)
        self.widget_10 = QWidget(self.eye)
        self.widget_10.setStyleSheet("border:2px solid white")
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QSize(0, 0))
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2 = QGridLayout(self.widget_10)
        #self.gridLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_21 = QLabel(self.widget_10)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        self.label_21.setMinimumSize( QSize(0,0) );
        #self.label_21.setMaximumSize( QSize(16777215, 16777215) );
        self.label_21.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(30)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 0)
        self.widget_16 = QWidget(self.widget_10)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setMinimumSize(QSize(0, 0))
        self.widget_16.setStyleSheet("border:1px solid white")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_14=QGridLayout(self.widget_16)
        self.gridLayout_2.addWidget(self.widget_16, 1, 0, 2, 2)
        self.horizontalLayout_11.addWidget(self.widget_10)
        self.stackedWidget.addWidget(self.eye)
        self.page_settings = QWidget()
        self.page_settings.setObjectName("page_settings")
        self.horizontalLayout_9 = QHBoxLayout(self.page_settings)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_3 = QWidget(self.page_settings)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_6 = QGridLayout(self.widget_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_12 = QWidget(self.widget_3)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_7 = QGridLayout(self.widget_12)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QLabel(self.widget_12)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255,255,255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QLabel(self.widget_12)
        font = QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(225,225,225);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QLabel(self.widget_12)
        font = QFont()
        font.setFamily("Fira Code Light")
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(200,200,200);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 2, 0, 1, 1)
        self.widget_6 = QWidget(self.widget_12)
        self.widget_6.setObjectName("widget_6")
        self.pushButton_2 = MySwitch(self.widget_6)
        self.pushButton_2.setChecked(True)
        self.pushButton_2.setGeometry(QRect(50, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.widget_6, 3, 0, 1, 1)
        self.label_10 = QLabel(self.widget_12)
        font = QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(225, 225, 225);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QLabel(self.widget_12)
        font = QFont()
        font.setFamily("Fira Code Light")
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:  rgb(200,200,200);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 5, 0, 1, 1)
        self.widget_4 = QWidget(self.widget_12)
        self.widget_4.setObjectName("widget_4")
        self.pushButton_3 = MySwitch(self.widget_4)
        self.pushButton_3.setChecked(True)
        self.pushButton_3.setGeometry(QRect(60, 0, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.widget_4, 6, 0, 1, 1)
        self.label_12 = QLabel(self.widget_12)
        font = QFont()
        font.setFamily("Fira Code Light")
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 7, 0, 1, 1)
        self.widget_7 = QWidget(self.widget_12)
        self.widget_7.setObjectName("widget_7")
        self.pushButton = MySwitch(self.widget_7)
        self.pushButton.setChecked(True)
        self.pushButton.setGeometry(QRect(50, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.widget_7, 8, 0, 1, 1)
        self.label_27 = QLabel(self.widget_12)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 9, 0, 1, 1)
        self.label_26 = QLabel(self.widget_12)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 10, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_12, 0, 0, 1, 1)
        self.widget_11 = QWidget(self.widget_3)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_6.addWidget(self.widget_11, 0, 1, 1, 1)
        self.widget_5 = QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_8 = QGridLayout(self.widget_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_13 = QLabel(self.widget_5)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(30)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QLabel(self.widget_5)
        font = QFont()
        font.setFamily("Fira Code Light")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(20, 255, 236);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_16 = QLabel(self.widget_5)
        font = QFont()
        font.setFamily("Fira Code Light")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(20, 255, 236);\n"
"")
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_15 = QLabel(self.widget_5)
        font = QFont()
        font.setFamily("Fira Code Light")
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(20, 255, 236);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_18 = QLabel(self.widget_5)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_17 = QLabel(self.widget_5)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 0, 2, 1, 1)
        self.horizontalLayout_9.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.page_settings)
        self.page_mouth = QWidget()
        self.page_mouth.setObjectName("page_mouth")
        self.horizontalLayout_12 = QHBoxLayout(self.page_mouth)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget = QWidget(self.page_mouth)
        self.widget.setObjectName("widget")
        self.gridLayout_9 = QGridLayout(self.widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QLabel(self.widget)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QLabel(self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("border:2px solid white\n")
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QLabel(self.widget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_24 = QLabel(self.widget)
        font = QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(25)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_25 = QLabel(self.widget)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 4, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.widget)
        self.widget_2 = QWidget(self.page_mouth)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_10 = QGridLayout(self.widget_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_3 = QLabel(self.widget_2)
        font = QFont()
        font.setFamily("Fira Code Retina")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 0, 1, 1)
        self.widget_15 = QWidget(self.widget_2)
        self.verticalLayout_10=QGridLayout(self.widget_15)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setStyleSheet("border:1px solid white\n"
"")
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_10.addWidget(self.widget_15, 1, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.page_mouth)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_content)
        self.frame_grip = QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QSize(0, 25))
        #self.frame_grip.setMaximumSize(QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.frame_grip.setFrameShape(QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_6 = QHBoxLayout(self.frame_grip)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QFrame(self.frame_grip)
        self.frame_label_bottom.setFrameShape(QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_credits = QLabel(self.frame_label_bottom)
        font = QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(200,200,200);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_7.addWidget(self.label_credits)
        self.label_version = QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QSize(60, 50))
        font = QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(200,200,200);")
        self.label_version.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_7.addWidget(self.label_version)
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.frame_size_grip = QFrame(self.frame_grip)
        self.frame_size_grip.setMaximumSize(QSize(20, 20))
        self.frame_size_grip.setStyleSheet("QSizeGrip {\n"
"    background-image: url(:/16x16/icons/16x16/cil-size-grip.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}")
        self.frame_size_grip.setFrameShape(QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_6.addWidget(self.frame_size_grip)
        self.verticalLayout_4.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout.addWidget(self.frame_center)
        self.gridLayout_4.addWidget(self.frame_main, 0, 0, 1, 1)
        MainWindow2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow2)
        self.stackedWidget.setCurrentIndex(1)
        QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.label_title_bar_top.setText(_translate("MainWindow2", "Main Window - Base"))
        self.btn_minimize.setToolTip(_translate("MainWindow2", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("MainWindow2", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow2", "Close"))
        self.label_top_info_1.setText(_translate("MainWindow2", "Current Window"))
        self.label_top_info_2.setText(_translate("MainWindow2", "| HOME"))
        self.btn_mouth.setText(_translate("MainWindow2", "Mouth"))
        self.btn_new_user.setWhatsThis(_translate("MainWindow2", "<html><head/><body><p><img src=\":/16x16/icons/16x16/cil-eye-open.png\"/></p></body></html>"))
        self.btn_new_user.setText(_translate("MainWindow2", "EYE"))
        self.btn_open_file.setWhatsThis(_translate("MainWindow2", "<html><head/><body><p><img src=\":/20x20/icons/20x20/cil-home-open.png\"/></p></body></html>"))
        self.btn_open_file.setText(_translate("MainWindow2", "HOME"))
        self.label_user_icon.setText(_translate("MainWindow2", "FD"))
        self.btn_settings.setText(_translate("MainWindow2", "Open File"))
        self.lab_face.setText(_translate("MainWindow2", "Driver face"))
        self.label_6.setText(_translate("MainWindow2", "HOME"))
        self.title_face.setText(_translate("MainWindow2", "Driver Status"))
        self.general.setText(_translate("MainWindow2", "General status: <font color='#14FFEC'>Good</font>"))
        self.eye_2.setText(_translate("MainWindow2", "Eye State:<font color='#14FFEC'>Open</font>"))
        self.mouth.setText(_translate("MainWindow2", "Mouth State: <font color='#14FFEC'>Normal</font>"))
        self.label_20.setText(_translate("MainWindow2", "Eye"))
        self.label_22.setText(_translate("MainWindow2", "Status:<font color='#14FFEC'>Good</font>"))
        self.label_8.setText(_translate("MainWindow2", "Driver eye"))
        self.label_21.setText(_translate("MainWindow2", "EAR Curve"))
        self.label_5.setText(_translate("MainWindow2", "Settings"))
        self.label_7.setText(_translate("MainWindow2", "Mouth state"))
        self.label_9.setText(_translate("MainWindow2", "Set the system to detect any yawning state"))
        self.pushButton_2.setText(_translate("MainWindow2", "PushButton"))
        self.label_10.setText(_translate("MainWindow2", "Display Curves"))
        self.label_11.setText(_translate("MainWindow2", "MAR Curve"))
        self.pushButton_3.setText(_translate("MainWindow2", "PushButton"))
        self.label_12.setText(_translate("MainWindow2", "Eye Aspect ratio"))
        self.pushButton.setText(_translate("MainWindow2", "PushButton"))
        self.label_13.setText(_translate("MainWindow2", "App"))
        self.label_14.setText(_translate("MainWindow2", "About"))
        self.label_16.setText(_translate("MainWindow2", "Help"))
        self.label_15.setText(_translate("MainWindow2", "FeedBack"))
        self.label_2.setText(_translate("MainWindow2", "Driver Mouth"))
        self.label.setText(_translate("MainWindow2", "Mouth"))
        self.label_24.setText(_translate("MainWindow2", "Status: Good"))
        self.label_3.setText(_translate("MainWindow2", "MAR Curve"))
        self.label_credits.setText(_translate("MainWindow2", "Registered by: Hamed LAOUZ"))
        self.label_version.setText(_translate("MainWindow2", "v1.0.0"))



